"""Writer agent — drafts a tailored German cover letter.

Sprint 1 implementation: template fill-in, no LLM. Sprint 3 replaces this
with an LLM call using the prompt at `prompts/writer.md`. The schema does
not change between sprints.
"""

from __future__ import annotations

from datetime import date

from job_agent.schemas import GeneratedApplication, JobPosting, MatchResult, UserProfile
from job_agent.utils.logging import get_logger

log = get_logger(__name__)


_TEMPLATE = """\
**Bewerbung: {title} — {company}**

Sehr geehrte Damen und Herren,

mit großem Interesse habe ich Ihre Stellenausschreibung als **{title}**
gelesen. Als {headline} aus {location} bringe ich folgende von Ihnen
gewünschte Qualifikationen mit: {matched_skills}.

{rationale}

Über die Möglichkeit, mich in einem persönlichen Gespräch vorzustellen,
würde ich mich sehr freuen.

Mit freundlichen Grüßen
{name}

---
*Generated by Job Application Agent on {today}. Sprint-1 template draft —
will be replaced by an LLM-tailored letter in Sprint 3.*
"""


def run_writer(
    job: JobPosting,
    match: MatchResult,
    profile: UserProfile,
) -> GeneratedApplication:
    """Produce a tailored application for one (job, match) pair."""
    matched_str = ", ".join(match.matched_skills) if match.matched_skills else "—"
    letter = _TEMPLATE.format(
        title=job.title,
        company=job.company,
        headline=profile.headline,
        location=profile.location,
        matched_skills=matched_str,
        rationale=match.rationale,
        name=profile.name,
        today=date.today().isoformat(),
    )

    quality = {
        "name_correct": profile.name.lower() in letter.lower(),
        "no_placeholders": "{{" not in letter and "}}" not in letter,
        "length_ok": 200 <= len(letter) <= 4000,
        "mentions_job_title": job.title.lower() in letter.lower(),
    }

    app = GeneratedApplication(
        job_id=job.id,
        cover_letter_md=letter,
        tailored_cv_path=None,  # Sprint 3 will populate this
        generated_at=date.today(),
        quality_checks=quality,
    )
    log.info("[writer] drafted application for %s (checks=%s)", job.id, quality)
    return app
